dotfiles update & add notdot

diff --git a/git_template/hooks/pre-commit b/git_template/hooks/pre-commit
--- a/git_template/hooks/pre-commit
+++ b/git_template/hooks/pre-commit
@@ -1,7 +1,12 @@
 #!/bin/sh
-
-local_hook="$HOME"/.git_template.local/hooks/pre-commit
-
-if [ -f "$local_hook" ]; then
-  . "$local_hook"
+# f2ehook
+PATH="/Users/jiewei.ljw/.nvm/versions/node/v6.2.2/lib/node_modules/tnpm/node_modules/npm/bin/node-gyp-bin:/Users/jiewei.ljw/work/dev/ae-mobile/node_modules/@ali/f2ehint-hook/node_modules/.bin:/Users/jiewei.ljw/work/dev/ae-mobile/node_modules/.bin:/Users/jiewei.ljw/.nvm/versions/node/v6.2.2/bin:/Users/jiewei.ljw/.nvm/versions/node/v6.2.2/bin:/opt/subversion/bin:/Users/jiewei.ljw/.rbenv/shims:/Users/jiewei.ljw/.jenv/shims:/Users/jiewei.ljw/.rbenv/bin:/Users/jiewei.ljw/.jenv/bin:/Users/jiewei.ljw/maven3/bin:/Users/jiewei.ljw/maven/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
+[ -f package.json ] && cat package.json | grep -q '"commithook"\s*:'
+[ $? -ne 0 ] && exit 0
+npm run commithook --silent
+if [ $? -ne 0 ]; then
+  echo
+  echo "git-hook: pre-commit hook failed (add --no-verify to bypass)"
+  echo
+  exit 1
 fi
